stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/train.csv
    params:
      - seed
      - data
      - split
    outs:
      - data/processed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
    params:
      - seed
      - data.target
      - train
    outs:
      - models/model.joblib

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.joblib
      - data/processed/test.csv
    params:
      - data.target
    metrics:
      - metrics.json:
          cache: false