[project]
name = "trio-mlops-collab"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "dvc[gdrive]>=3.67.1",
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "pyopenssl>=24",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.9.1",
]

[dependency-groups]
dev = [
    "dvc[s3]>=3.67.1",
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "jupytext>=1.19.5",
    "nbstripout>=0.9.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
